from langchain_google_genai.chat_models import ChatGoogleGenerativeAI
from typing import Dict, Any, Optional
import os
from dotenv import load_dotenv

load_dotenv() # Load environment variables from .env file

# Retrieve API key from environment
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

class GeminiCodingAgent:
    """
    A coding agent powered by Gemini to implement features, fix bugs, and refactor code.
    """

    def __init__(self):
        if not GEMINI_API_KEY or GEMINI_API_KEY == "YOUR_GEMINI_API_KEY":
            print("WARNING: GEMINI_API_KEY not configured. Using simulated API calls.")
            self.model = None # Indicates using simulated calls
        else:
            self.model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=GEMINI_API_KEY)

    def _make_gemini_api_call(self, prompt: str) -> str:
        """
        Makes a call to the Gemini API or simulates it if API key is not configured.
        """
        if self.model:
            try:
                response = self.model.invoke(prompt)
                return response.content
            except Exception as e:
                print(f"Error making Gemini API call: {e}. Falling back to simulated response.")
                # This is a hardcoded response for demonstration purposes.
                return "\n# This code was generated by the Gemini Coding Agent\ndef new_feature():\n    print(\"This is a new feature!\")\n"
        else:
            print(f"--- Simulating Gemini API call with prompt: ---\n{prompt}\n-------------------------------------------")
            # This is a hardcoded response for demonstration purposes.
            return "\n# This code was generated by the Gemini Coding Agent\ndef new_feature():\n    print(\"This is a new feature!\")\n"

    def generate_code(self, task_description: str, file_path: str, git_context: Optional[Dict[str, Any]] = None) -> str:
        """
        Generates code to implement a new feature or fix a bug.
        """
        if git_context:
            print(f"GeminiCodingAgent received Git context: {git_context}")
        
        prompt = f"""
        **Task:** {task_description}

        **File to modify:** {file_path}

        **Instructions:**
        1.  Analyze the existing code in the file (if any).
        2.  Generate the Python code to implement the requested feature.
        3.  Ensure the code is well-structured and follows best practices.
        4.  Provide only the code, without any explanations or markdown.
        """
        generated_code = self._make_gemini_api_call(prompt)
        return generated_code

    def refactor_code(self, task_description: str, file_path: str, code_to_refactor: str, git_context: Optional[Dict[str, Any]] = None) -> str:
        """
        Refactors existing code to improve its structure, performance, or readability.
        """
        if git_context:
            print(f"GeminiCodingAgent received Git context: {git_context}")
            
        prompt = f"""
        **Task:** {task_description}

        **File to modify:** {file_path}

        **Code to refactor:**
        ```python
        {code_to_refactor}
        ```

        **Instructions:**
        1.  Analyze the provided code and the refactoring task.
        2.  Generate the refactored Python code.
        3.  Ensure the refactored code is functionally equivalent to the original.
        4.  Provide only the code, without any explanations or markdown.
        """
        refactored_code = self._make_gemini_api_call(prompt)
        return refactored_code

# Example usage (for testing purposes)
if __name__ == "__main__":
    agent = GeminiCodingAgent()

    # --- Example 1: Generate a new feature ---
    print("--- Example 1: Generate a new feature ---")
    task1 = "Implement a new feature to print a message."
    file1 = "my_new_feature.py"
    generated_code = agent.generate_code(task1, file1)
    print(f"Generated code for {file1}:\n```python\n{generated_code}\n```")

    # --- Example 2: Refactor existing code ---
    print("\n--- Example 2: Refactor existing code ---")
    task2 = "Refactor the 'add' function to be more concise."
    file2 = "my_module.py"
    code_to_refactor = """
def add(a, b):
    result = a + b
    return result
"""
    refactored_code = agent.refactor_code(task2, file2, code_to_refactor)
    print(f"Refactored code for {file2}:\n```python\n{refactored_code}\n```")